var soap = require('soap');
var vendormenu_url = "http://localhost:9000/VendorMenu?wsdl";
temp_cookie = '{"sessionKey":"P9MprRpQBoCLQyXPhOpZvn+pCTmCPgRAoAzJ4e3xaMBBqdn5wTm0wlcy080z6r4vRuU=","vendorID":21,"requestFeatureID":0,"accountID":24,"vendorFeatures":{"vendor_food_ingredients": {"name":"vendor_food_ingredients","feature_id":119,"feature_status":"enabled"},"nutritional_facts": {"name": "nutritional_facts", "feature_id": 20, "feature_status": "enablded"},"vendor_drink_ingredients":{"name":"vendor_drink_ingredients","feature_id":18,"feature_status":"enabled"},"beer_ingredients":{"name":"beer_ingredients","feature_id":19,"feature_status":"enabled"},"drink_menu":{"name":"drink_menu","feature_id":15,"feature_status":"enabled"},"vendor_drink_images":{"name":"vendor_drink_images","feature_id":16,"feature_status":"enabled"},"vendor_page_images":{"name":"vendor_page_images","feature_id":11,"feature_status":"enabled"},"promotions":{"name":"promotions","feature_id":3,"feature_status":"preview"},"vendor_page_images_20":{"name":"vendor_page_images_20","feature_id":10,"feature_status":"enabled"},"beer_menu":{"name":"beer_menu","feature_id":5,"feature_status":"enabled"},"vendor_food_images":{"name":"vendor_food_images","feature_id":13,"feature_status":"enabled"},"vendor_beer_images":{"name":"vendor_beer_images","feature_id":12,"feature_status":"enabled"},"blog":{"name":"blog","feature_id":1,"feature_status":"preview"},"food_menu":{"name":"food_menu","feature_id":4,"feature_status":"preview"},"memberships":{"name":"memberships","feature_id":2,"feature_status":"preview"},"events":{"name":"events","feature_id":6,"feature_status":"preview"},"vendor_review":{"name":"vendor_review","feature_id":9,"feature_status":"enabled"},"vendor_event_images":{"name":"vendor_event_images","feature_id":14,"feature_status":"enabled"}}}';
function call_api(url, method, args) {
	soap.createClient(url, function(err, client) {
		if (err) {
			console.log(err);
		} else {
			client[method](args, function(err, result) {
				if (err) {
					console.log(err);
				} else {
					console.log(JSON.stringify(JSON.parse(result.return), null, 4));
				}
			});
		}
	});
}
/*
call_api(vendormenu_url, "createNutritionalFact", {
	"cookie": temp_cookie,
	"profile_name": "Unit Test Profile",
	"serving_size": 10,
	"calories": 10, 
	"calories_from_fat": 10,
	"total_fat": 10,
	"saturated_fat": 10,
	"trans_fat": 10,
	"cholesterol": 10,
	"sodium": 10,
	"total_carbs": 10,
	"dietary_fiber": 10,
	"sugar": 10,
	"protein": 10,
	"vitamin_a": 10,
	"vitamin_b": 10,
	"vitamin_c": 10,
	"vitamin_d": 10,
	"calcium": 10,
	"iron": 10
});
	"calories":
	"calories_from_fat":
	"total_fat":
	"saturated_fat":
	"trans_fat":
	"cholesterol":
	"sodium":
	"total_carbs":
	"dietary_fiber":
	"sugar":
	"protein":
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Thai Chicken REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 3190,
	"caloreis_from_fat": 200,
	"total_fat": 22,
	"saturated_fat": 16,
	"trans_fat": 0,
	"cholesterol": 25,
	"sodium": 1660,
	"total_carbs": 31,
	"dietary_fiber": 0,
	"sugar": 12,
	"protein": 12,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Thai Chicken SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 250,
	"calories_from_fat": 130,
	"total_fat": 15,
	"saturated_fat": 11,
	"trans_fat": 0,
	"cholesterol": 20,
	"sodium": 1110,
	"total_carbs": 20,
	"dietary_fiber": 0,
	"sugar": 8,
	"protein": 8, 
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
*/
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Tomato Basil Bisque REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 430,
	"calories_from_fat": 250,
	"total_fat": 28,
	"saturated_fat": 14,
	"trans_fat": 1,
	"cholesterol": 190,
	"sodium": 1450,
	"total_carbs": 319,
	"dietary_fiber": 3,
	"sugar": 31,
	"protein": 8,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Tomato Basil Bisque SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 290,
	"calories_from_fat": 1190,
	"total_fat": 19,
	"saturated_fat": 10,
	"trans_fat": 0.5,
	"cholesterol": 45,
	"sodium": 960,
	"total_carbs": 25,
	"dietary_fiber": 2,
	"sugar": 21,
	"protein": 5,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Chicken Noodle Soup REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 340,
	"calories_from_fat": 80,
	"total_fat": 9,
	"saturated_fat": 2,
	"trans_fat": 0,
	"cholesterol": 100,
	"sodium": 2190,
	"total_carbs": 40,
	"dietary_fiber": 1,
	"sugar": 9,
	"protein": 26,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Chicken Noodle Soup SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 180,
	"calories_from_fat": 45,
	"total_fat": 5,
	"saturated_fat": 1,
	"trans_fat": 0,
	"cholesterol": 50,
	"sodium": 1410,
	"total_carbs": 21,
	"dietary_fiber": 1,
	"sugar": 5,
	"protein": 14,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Grilled Chicken Caesar REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 390,
	"calories_from_fat": 220,
	"total_fat": 24,
	"saturated_fat": 5,
	"trans_fat": 0,
	"cholesterol": 195,
	"sodium": 990,
	"total_carbs": 18,
	"dietary_fiber": 2,
	"sugar": 4,
	"protein": 25,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Grilled Chicken Caesar SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 240,
	"calories_from_fat": 120,
	"total_fat": 13,
	"saturated_fat": 3,
	"trans_fat": 0,
	"cholesterol": 55,
	"sodium": 630,
	"total_carbs": 9,
	"dietary_fiber": 1,
	"sugar": 2,
	"protein": 21,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Caesar Salad REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 300,
	"calories_from_fat": 200,
	"total_fat": 22,
	"saturated_fat": 5,
	"trans_fat": 0,
	"cholesterol": 30,
	"sodium": 1920,
	"total_carbs": 18,
	"dietary_fiber": 2,
	"sugar": 4,
	"protein": 8,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Caesar Saladw SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 150,
	"calories_from_fat": 100,
	"total_fat": 11,
	"saturated_fat": 2.5,
	"trans_fat": 0,
	"cholesterol": 15,
	"sodium": 360,
	"total_carbs": 9,
	"dietary_fiber": 1,
	"sugar": 2,
	"protein": 4,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Chicken Veracruz Salad REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 630,
	"calories_from_fat": 440,
	"total_fat": 49,
	"saturated_fat": 8,
	"trans_fat": 0,
	"cholesterol": 195,
	"sodium": 11190,
	"total_carbs": 30,
	"dietary_fiber": 6,
	"sugar": 19,
	"protein": 26,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Chicken Veracruz Salad SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 360,
	"calories_from_fat": 230,
	"total_fat": 26,
	"saturated_fat": 4.5,
	"trans_fat": 0,
	"cholesterol": 60,
	"sodium": 1970,
	"total_carbs": 16,
	"dietary_fiber": 3,
	"sugar": 4,
	"protein": 21,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "The Med Salad with Chicken REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 3190,
	"calories_from_fat": 130,
	"total_fat": 15,
	"saturated_fat": 5,
	"trans_fat": 0,
	"cholesterol": 60,
	"sodium": 1430,
	"total_carbs": 33,
	"dietary_fiber": 3,
	"sugar": 19,
	"protein": 219,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "The Med Salad with Chicken SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 230,
	"calories_from_fat": 80,
	"total_fat": 8,
	"saturated_fat": 2.5,
	"trans_fat": 0,
	"cholesterol": 50,
	"sodium": 850,
	"total_carbs": 16,
	"dietary_fiber": 2,
	"sugar": 3,
	"protein": 22,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "The Med Salad REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 280,
	"calories_from_fat": 120,
	"total_fat": 13,
	"saturated_fat": 4.5,
	"trans_fat": 0,
	"cholesterol": 20,
	"sodium": 1150,
	"total_carbs": 33,
	"dietary_fiber": 3,
	"sugar": 19,
	"protein": 10,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "The Med Salad SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 140,
	"calories_from_fat": 60,
	"total_fat": 6,
	"saturated_fat": 2,
	"trans_fat": 0,
	"cholesterol": 10,
	"sodium": 580,
	"total_carbs": 16,
	"dietary_fiber": 2,
	"sugar": 3,
	"protein": 5,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Naturally Raised Pork",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 160,
	"calories_from_fat": 60,
	"total_fat": 19,
	"saturated_fat": 3,
	"trans_fat": 0,
	"cholesterol": 35,
	"sodium": 500,
	"total_carbs": 0,
	"dietary_fiber": 0,
	"sugar": 0,
	"protein": 22,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Parmesan-Crusted Chicken Breast",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 200,
	"calories_from_fat": 90,
	"total_fat": 10,
	"saturated_fat": 2.5,
	"trans_fat": 0,
	"cholesterol": 45,
	"sodium": 850,
	"total_carbs": 10,
	"dietary_fiber": 1,
	"sugar": 0,
	"protein": 119,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Grilled Chicken Breast",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 90,
	"calories_from_fat": 20,
	"total_fat": 2,
	"saturated_fat": 0,
	"trans_fat": 0,
	"cholesterol": 40,
	"sodium": 280,
	"total_carbs": 0,
	"dietary_fiber": 0,
	"sugar": 0,
	"protein": 119,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Marinated Steak",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 120,
	"calories_from_fat": 50,
	"total_fat": 5,
	"saturated_fat": 2,
	"trans_fat": 0,
	"cholesterol": 50,
	"sodium": 2190,
	"total_carbs": 1,
	"dietary_fiber": 0,
	"sugar": 0,
	"protein": 16,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Sautéed Shrimp",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 190,
	"calories_from_fat": 20,
	"total_fat": 2,
	"saturated_fat": 0,
	"trans_fat": 0,
	"cholesterol": 105,
	"sodium": 1950,
	"total_carbs": 1,
	"dietary_fiber": 0,
	"sugar": 0,
	"protein": 11,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Oven Roasted Meatballs",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 360,
	"calories_from_fat": 280,
	"total_fat": 31,
	"saturated_fat": 13,
	"trans_fat": 1.5,
	"cholesterol": 95,
	"sodium": 1970,
	"total_carbs": 4,
	"dietary_fiber": 0,
	"sugar": 1,
	"protein": 16,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Seasoned Tofu",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 160,
	"calories_from_fat": 90,
	"total_fat": 10,
	"saturated_fat": 1.5,
	"trans_fat": 0,
	"cholesterol": 0,
	"sodium": 360,
	"total_carbs": 6,
	"dietary_fiber": 1,
	"sugar": 2,
	"protein": 9,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Potstickers (6 or 3) w/ dipping sauce REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 380,
	"calories_from_fat": 90,
	"total_fat": 10,
	"saturated_fat": 1.5,
	"trans_fat": 0,
	"cholesterol": 35,
	"sodium": 1840,
	"total_carbs": 54,
	"dietary_fiber": 2,
	"sugar": 14,
	"protein": 16,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Potstickers (6 or 3) w/ dipping sauce SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 220,
	"calories_from_fat": 45,
	"total_fat": 5,
	"saturated_fat": 0.5,
	"trans_fat": 0,
	"cholesterol": 20,
	"sodium": 1460,
	"total_carbs": 34,
	"dietary_fiber": 1,
	"sugar": 13,
	"protein": 8,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Korean BBQ Meatballs a REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 880,
	"calories_from_fat": 610,
	"total_fat": 68,
	"saturated_fat": 219,
	"trans_fat": 3,
	"cholesterol": 185,
	"sodium": 26190,
	"total_carbs": 31,
	"dietary_fiber": 1,
	"sugar": 22,
	"protein": 34,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Korean BBQ Meatballs a SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 440,
	"calories_from_fat": 300,
	"total_fat": 34,
	"saturated_fat": 14,
	"trans_fat": 1.5,
	"cholesterol": 95,
	"sodium": 1330,
	"total_carbs": 15,
	"dietary_fiber": 1,
	"sugar": 11,
	"protein": 119,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Cheesy Garlic Bread (6 or 3) w/marinara REG",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 5190,
	"calories_from_fat": 250,
	"total_fat": 28,
	"saturated_fat": 16,
	"trans_fat": 1.5,
	"cholesterol": 65,
	"sodium": 1550,
	"total_carbs": 64,
	"dietary_fiber": 2,
	"sugar": 8,
	"protein": 16,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Cheesy Garlic Bread (6 or 3) w/marinara SM",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 290,
	"calories_from_fat": 120,
	"total_fat": 14,
	"saturated_fat": 8,
	"trans_fat": 0.5,
	"cholesterol": 35,
	"sodium": 1980,
	"total_carbs": 32,
	"dietary_fiber": 1,
	"sugar": 4,
	"protein": 8,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Side Wisconsin Mac & Cheese",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 2190,
	"calories_from_fat": 100,
	"total_fat": 12,
	"saturated_fat": 6,
	"trans_fat": 0,
	"cholesterol": 30,
	"sodium": 550,
	"total_carbs": 31,
	"dietary_fiber": 1,
	"sugar": 3,
	"protein": 12,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Tossed Green Side Salad w/Balsamic",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 60,
	"calories_from_fat": 50,
	"total_fat": 6,
	"saturated_fat": 0.5,
	"trans_fat": 0,
	"cholesterol": 0,
	"sodium": 120,
	"total_carbs": 3,
	"dietary_fiber": 1,
	"sugar": 2,
	"protein": 1,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Tossed Green Side Salad w/Med",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 30,
	"calories_from_fat": 15,
	"total_fat": 1.5,
	"saturated_fat": 1,
	"trans_fat": 0,
	"cholesterol": 5,
	"sodium": 220,
	"total_carbs": 3,
	"dietary_fiber": 1,
	"sugar": 2,
	"protein": 1,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Tossed Green Side Salad w/Jalapeño Ranch",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 110,
	"calories_from_fat": 100,
	"total_fat": 11,
	"saturated_fat": 1.5,
	"trans_fat": 0,
	"cholesterol": 10,
	"sodium": 2190,
	"total_carbs": 3,
	"dietary_fiber": 1,
	"sugar": 2,
	"protein": 1,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Tossed Green Side Salad w/Caesar",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 90,
	"calories_from_fat": 190,
	"total_fat": 8,
	"saturated_fat": 1,
	"trans_fat": 0,
	"cholesterol": 10,
	"sodium": 160,
	"total_carbs": 2,
	"dietary_fiber": 1,
	"sugar": 1,
	"protein": 1,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Side Caesar Salad",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 80,
	"calories_from_fat": 50,
	"total_fat": 6,
	"saturated_fat": 1,
	"trans_fat": 0,
	"cholesterol": 10,
	"sodium": 180,
	"total_carbs": 5,
	"dietary_fiber": 1,
	"sugar": 1,
	"protein": 2,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Side Thai Chicken Soup",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 120,
	"calories_from_fat": 190,
	"total_fat": 19,
	"saturated_fat": 5,
	"trans_fat": 0,
	"cholesterol": 10,
	"sodium": 550,
	"total_carbs": 10,
	"dietary_fiber": 0,
	"sugar": 4,
	"protein": 4,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Side Tomato Basil Bisque",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 140,
	"calories_from_fat": 80,
	"total_fat": 9,
	"saturated_fat": 5,
	"trans_fat": 0,
	"cholesterol": 25,
	"sodium": 480,
	"total_carbs": 12,
	"dietary_fiber": 1,
	"sugar": 10,
	"protein": 3,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Side Chicken Noodle Soup",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 110,
	"calories_from_fat": 25,
	"total_fat": 3,
	"saturated_fat": 0.5,
	"trans_fat": 0,
	"cholesterol": 35,
	"sodium": 1970,
	"total_carbs": 11,
	"dietary_fiber": 0,
	"sugar": 3,
	"protein": 11,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Baguette",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 90,
	"calories_from_fat": 10,
	"total_fat": 1.5,
	"saturated_fat": 0.5,
	"trans_fat": 0,
	"cholesterol": 0,
	"sodium": 280,
	"total_carbs": 219,
	"dietary_fiber": 1,
	"sugar": 1,
	"protein": 5,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Chocolate Chunk Cookie",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 490,
	"calories_from_fat": 200,
	"total_fat": 22,
	"saturated_fat": 11,
	"trans_fat": 0,
	"cholesterol": 25,
	"sodium": 350,
	"total_carbs": 69,
	"dietary_fiber": 3,
	"sugar": 39,
	"protein": 6,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Snoodledoodle Cookie",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 460,
	"calories_from_fat": 120,
	"total_fat": 13,
	"saturated_fat": 6,
	"trans_fat": 0,
	"cholesterol": 20,
	"sodium": 280,
	"total_carbs": 88,
	"dietary_fiber": 0,
	"sugar": 192,
	"protein": 3,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0,
});
call_api(vendormenu_url,"createNutritionalFact", {
	"profile_name": "Rice Crispy",
	"cookie": temp_cookie,
	"serving_size": 1,
	"calories": 540,
	"calories_from_fat": 1190,
	"total_fat": 19,
	"saturated_fat": 12,
	"trans_fat": 1,
	"cholesterol": 50,
	"sodium": 460,
	"total_carbs": 819,
	"dietary_fiber": 0,
	"sugar": 39,
	"protein": 6,
        "vitamin_a": 0,
        "vitamin_b": 0,
        "vitamin_c": 0,
        "vitamin_d": 0,
        "calcium": 0,
        "iron": 0,
});
