var soap = require('soap');
var vendormenu_url = "http://localhost:9000/VendorMenu?wsdl";
temp_cookie = '{"sessionKey":"P9MprRpQBoCLQyXPhOpZvn+pCTmCPgRAoAzJ4e3xaMBBqdn5wTm0wlcy080z6r4vRuU=","vendorID":21,"requestFeatureID":0,"accountID":24,"vendorFeatures":{"vendor_food_ingredients": {"name":"vendor_food_ingredients","feature_id":17,"feature_status":"enabled"},"nutritional_facts": {"name": "nutritional_facts", "feature_id": 20, "feature_status": "enablded"},"vendor_drink_ingredients":{"name":"vendor_drink_ingredients","feature_id":18,"feature_status":"enabled"},"beer_ingredients":{"name":"beer_ingredients","feature_id":19,"feature_status":"enabled"},"drink_menu":{"name":"drink_menu","feature_id":15,"feature_status":"enabled"},"vendor_drink_images":{"name":"vendor_drink_images","feature_id":16,"feature_status":"enabled"},"vendor_page_images":{"name":"vendor_page_images","feature_id":11,"feature_status":"enabled"},"promotions":{"name":"promotions","feature_id":3,"feature_status":"preview"},"vendor_page_images_20":{"name":"vendor_page_images_20","feature_id":10,"feature_status":"enabled"},"beer_menu":{"name":"beer_menu","feature_id":5,"feature_status":"enabled"},"vendor_food_images":{"name":"vendor_food_images","feature_id":13,"feature_status":"enabled"},"vendor_beer_images":{"name":"vendor_beer_images","feature_id":12,"feature_status":"enabled"},"blog":{"name":"blog","feature_id":1,"feature_status":"preview"},"food_menu":{"name":"food_menu","feature_id":4,"feature_status":"preview"},"memberships":{"name":"memberships","feature_id":2,"feature_status":"preview"},"events":{"name":"events","feature_id":6,"feature_status":"preview"},"vendor_review":{"name":"vendor_review","feature_id":9,"feature_status":"enabled"},"vendor_event_images":{"name":"vendor_event_images","feature_id":14,"feature_status":"enabled"}}}';
function call_api(url, method, args) {
	soap.createClient(url, function(err, client) {
		if (err) {
			console.log(err);
		} else {
			client[method](args, function(err, result) {
				if (err) {
					console.log(err);
				} else {
					console.log(JSON.stringify(JSON.parse(result.return), null, 4));
				}
			});
		}
	});
}
/*
call_api(vendormenu_url, "createNutritionalFact", {
	"cookie": temp_cookie,
	"profile_name": "Unit Test Profile",
	"serving_size": 10,
	"calories": 10, 
	"calories_from_fat": 10,
	"total_fat": 10,
	"saturated_fat": 10,
	"trans_fat": 10,
	"cholesterol": 10,
	"sodium": 10,
	"total_carbs": 10,
	"dietary_fiber": 10,
	"sugar": 10,
	"protein": 10,
	"vitamin_a": 10,
	"vitamin_b": 10,
	"vitamin_c": 10,
	"vitamin_d": 10,
	"calcium": 10,
	"iron": 10
});
*/

call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Penne Rosa with parmesan RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 360,
	"calories_from_fat": 110,
	"total_fat": 13, 
	"saturated_fat": 6,
	"trans_fat": 0, 
	"cholesterol": 30, 
	"sodium": 440, 
	"total_carbs": 51, 
	"dietary_fiber": 3, 
	"sugar": 6, 
	"protein": 11,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Penne Rosa with parmesan SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 720, 
	"calories_from_fat": 230, 
	"total_fat": 25, 
	"saturated_fat": 11, 
	"trans_fat": 1, 
	"cholesterol": 55, 
	"sodium": 820, 
	"total_carbs": 102, 
	"dietary_fiber": 5, 
	"sugar": 13, 
	"protein": 23, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Penne Rosa with feta RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 360, 
	"calories_from_fat": 110, 
	"total_fat": 13, 
	"saturated_fat": 6, 
	"trans_fat": 0, 
	"cholesterol": 30, 
	"sodium": 440, 
	"total_carbs": 51, 
	"dietary_fiber": 3, 
	"sugar": 6, 
	"protein": 11,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Penne Rosa with feta SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 720, 
	"calories_from_fat": 230, 
	"total_fat": 25, 
	"saturated_fat": 11, 
	"trans_fat": 1, 
	"cholesterol": 55, 
	"sodium": 820, 
	"total_carbs": 102, 
	"dietary_fiber": 5, 
	"sugar": 13, 
	"protein": 23, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Japanese Pan Noodles RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 330, 
	"calories_from_fat": 70, 
	"total_fat": 8, 
	"saturated_fat": 0.5, 
	"trans_fat": 0, 
	"cholesterol": 0, 
	"sodium": 1000, 
	"total_carbs": 56, 
	"dietary_fiber": 2, 
	"sugar": 11, 
	"protein": 7,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Japanese Pan Noodles SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 660, 
	"calories_from_fat": 150, 
	"total_fat": 16, 
	"saturated_fat": 1.5, 
	"trans_fat": 0, 
	"cholesterol": 0, 
	"sodium": 2010, 
	"total_carbs": 111, 
	"dietary_fiber": 5, 
	"sugar": 23, 
	"protein": 13, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Wisconsin Mac & Cheese RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 490, 
	"calories_from_fat": 170, 
	"total_fat": 19, 
	"saturated_fat": 10, 
	"trans_fat": 0.5, 
	"cholesterol": 50, 
	"sodium": 780, 
	"total_carbs": 59, 
	"dietary_fiber": 2, 
	"sugar": 5, 
	"protein": 21,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Wisconsin Mac & Cheese SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 980, 
	"calories_from_fat": 340, 
	"total_fat": 38, 
	"saturated_fat": 20, 
	"trans_fat": 1, 
	"cholesterol": 95, 
	"sodium": 1560, 
	"total_carbs": 119, 
	"dietary_fiber": 5, 
	"sugar": 11, 
	"protein": 42, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Truffle Mac RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 530, 
	"calories_from_fat": 190, 
	"total_fat": 21, 
	"saturated_fat": 9, 
	"trans_fat": 0.5, 
	"cholesterol": 35, 
	"sodium": 1080, 
	"total_carbs": 65, 
	"dietary_fiber": 3, 
	"sugar": 7, 
	"protein": 21,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Truffle Mac SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 1070, 
	"calories_from_fat": 390, 
	"total_fat": 43, 
	"saturated_fat": 17, 
	"trans_fat": 1, 
	"cholesterol": 75, 
	"sodium": 2150, 
	"total_carbs": 131, 
	"dietary_fiber": 6, 
	"sugar": 13, 
	"protein": 41, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Buffalo Chicken Mac RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 660, 
	"calories_from_fat": 230, 
	"total_fat": 26, 
	"saturated_fat": 10, 
	"trans_fat": 0, 
	"cholesterol": 85, 
	"sodium": 1980, 
	"total_carbs": 70, 
	"dietary_fiber": 3, 
	"sugar": 6, 
	"protein": 36,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Buffalo Chicken Mac SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 1110, 
	"calories_from_fat": 370, 
	"total_fat": 41, 
	"saturated_fat": 18, 
	"trans_fat": 1, 
	"cholesterol": 120, 
	"sodium": 3110, 
	"total_carbs": 130, 
	"dietary_fiber": 6, 
	"sugar": 11, 
	"protein": 54, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "BBQ Pork Mac RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 690, 
	"calories_from_fat": 240, 
	"total_fat": 27, 
	"saturated_fat": 13, 
	"trans_fat": 0.5, 
	"cholesterol": 80, 
	"sodium": 1380, 
	"total_carbs": 65, 
	"dietary_fiber": 3, 
	"sugar": 9, 
	"protein": 43,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "BBQ Pork Mac SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 1210, 
	"calories_from_fat": 430, 
	"total_fat": 47, 
	"saturated_fat": 22, 
	"trans_fat": 1, 
	"cholesterol": 130, 
	"sodium": 2270, 
	"total_carbs": 129, 
	"dietary_fiber": 5, 
	"sugar": 18, 
	"protein": 64, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pesto Cavatappi with parmesan RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 380, 
	"calories_from_fat": 140, 
	"total_fat": 16, 
	"saturated_fat": 5, 
	"trans_fat": 0, 
	"cholesterol": 20, 
	"sodium": 440, 
	"total_carbs": 47, 
	"dietary_fiber": 3, 
	"sugar": 4, 
	"protein": 12,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pesto Cavatappi with parmesan SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 750, 
	"calories_from_fat": 290, 
	"total_fat": 32, 
	"saturated_fat": 10, 
	"trans_fat": 0, 
	"cholesterol": 45, 
	"sodium": 870, 
	"total_carbs": 93, 
	"dietary_fiber": 6, 
	"sugar": 8, 
	"protein": 23, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pesto Cavatappi with feta RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 380, 
	"calories_from_fat": 140, 
	"total_fat": 16, 
	"saturated_fat": 5, 
	"trans_fat": 0, 
	"cholesterol": 20, 
	"sodium": 440, 
	"total_carbs": 47, 
	"dietary_fiber": 3, 
	"sugar": 4, 
	"protein": 12,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pesto Cavatappi with feta SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 750, 
	"calories_from_fat": 290, 
	"total_fat": 32, 
	"saturated_fat": 10, 
	"trans_fat": 0, 
	"cholesterol": 45, 
	"sodium": 870, 
	"total_carbs": 93, 
	"dietary_fiber": 6, 
	"sugar": 8, 
	"protein": 23, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pad Thai RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 620, 
	"calories_from_fat": 320, 
	"total_fat": 35, 
	"saturated_fat": 6, 
	"trans_fat": 0, 
	"cholesterol": 170, 
	"sodium": 650, 
	"total_carbs": 65, 
	"dietary_fiber": 2, 
	"sugar": 15, 
	"protein": 10,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pad Thai SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 1240, 
	"calories_from_fat": 630, 
	"total_fat": 70, 
	"saturated_fat": 12, 
	"trans_fat": 0, 
	"cholesterol": 340, 
	"sodium": 1290, 
	"total_carbs": 129, 
	"dietary_fiber": 4, 
	"sugar": 30, 
	"protein": 19, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spaghetti & Meatballs RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 670, 
	"calories_from_fat": 350, 
	"total_fat": 39, 
	"saturated_fat": 15, 
	"trans_fat": 2, 
	"cholesterol": 100, 
	"sodium": 1170, 
	"total_carbs": 53, 
	"dietary_fiber": 2, 
	"sugar": 8, 
	"protein": 26,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spaghetti & Meatballs SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 980, 
	"calories_from_fat": 430, 
	"total_fat": 48, 
	"saturated_fat": 17, 
	"trans_fat": 2.5, 
	"cholesterol": 105, 
	"sodium": 1570, 
	"total_carbs": 101, 
	"dietary_fiber": 4, 
	"sugar": 16, 
	"protein": 35, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spaghetti RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 310, 
	"calories_from_fat": 80, 
	"total_fat": 9, 
	"saturated_fat": 2, 
	"trans_fat": 0.5, 
	"cholesterol": 5, 
	"sodium": 400, 
	"total_carbs": 49, 
	"dietary_fiber": 2, 
	"sugar": 8, 
	"protein": 10,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spaghetti SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 620, 
	"calories_from_fat": 150, 
	"total_fat": 17, 
	"saturated_fat": 4.5, 
	"trans_fat": 1, 
	"cholesterol": 15, 
	"sodium": 810, 
	"total_carbs": 97, 
	"dietary_fiber": 3, 
	"sugar": 16, 
	"protein": 19, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Thai Green Curry RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 390, 
	"calories_from_fat": 100, 
	"total_fat": 11, 
	"saturated_fat": 7, 
	"trans_fat": 0, 
	"cholesterol": 0, 
	"sodium": 760, 
	"total_carbs": 65, 
	"dietary_fiber": 3, 
	"sugar": 15, 
	"protein": 5,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Thai Green Curry SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 770, 
	"calories_from_fat": 210, 
	"total_fat": 23, 
	"saturated_fat": 14, 
	"trans_fat": 0, 
	"cholesterol": 0, 
	"sodium": 1530, 
	"total_carbs": 129, 
	"dietary_fiber": 6, 
	"sugar": 30, 
	"protein": 10, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Thai Green Curry with Shrimp RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 440, 
	"calories_from_fat": 100, 
	"total_fat": 12, 
	"saturated_fat": 7, 
	"trans_fat": 0, 
	"cholesterol": 105, 
	"sodium": 1370, 
	"total_carbs": 66, 
	"dietary_fiber": 3, 
	"sugar": 15, 
	"protein": 16,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Thai Green Curry with Shrimp SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 820, 
	"calories_from_fat": 210, 
	"total_fat": 23, 
	"saturated_fat": 14, 
	"trans_fat": 0, 
	"cholesterol": 105, 
	"sodium": 2140, 
	"total_carbs": 130, 
	"dietary_fiber": 6, 
	"sugar": 30, 
	"protein": 21, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Steak Stroganoff RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 580, 
	"calories_from_fat": 260, 
	"total_fat": 29, 
	"saturated_fat": 11, 
	"trans_fat": 0.5, 
	"cholesterol": 165, 
	"sodium": 690, 
	"total_carbs": 55, 
	"dietary_fiber": 3, 
	"sugar": 5, 
	"protein": 29,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Steak Stroganoff SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 1050, 
	"calories_from_fat": 470, 
	"total_fat": 53, 
	"saturated_fat": 21, 
	"trans_fat": 1, 
	"cholesterol": 275, 
	"sodium": 1110, 
	"total_carbs": 109, 
	"dietary_fiber": 5, 
	"sugar": 11, 
	"protein": 42, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Mushroom Stroganoff RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 470, 
	"calories_from_fat": 210, 
	"total_fat": 24, 
	"saturated_fat": 10, 
	"trans_fat": 0.5, 
	"cholesterol": 115, 
	"sodium": 420, 
	"total_carbs": 54, 
	"dietary_fiber": 3, 
	"sugar": 5, 
	"protein": 13,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Mushroom Stroganoff SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 810, 
	"calories_from_fat": 330, 
	"total_fat": 36, 
	"saturated_fat": 12, 
	"trans_fat": 0.5, 
	"cholesterol": 200, 
	"sodium": 620, 
	"total_carbs": 104, 
	"dietary_fiber": 5, 
	"sugar": 8, 
	"protein": 25, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Chipotle Adobo RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 410, 
	"calories_from_fat": 160, 
	"total_fat": 18, 
	"saturated_fat": 8, 
	"trans_fat": 0, 
	"cholesterol": 40, 
	"sodium": 1010, 
	"total_carbs": 53, 
	"dietary_fiber": 4, 
	"sugar": 7, 
	"protein": 11,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Chipotle Adobo SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 820, 
	"calories_from_fat": 320, 
	"total_fat": 35, 
	"saturated_fat": 16, 
	"trans_fat": 0.5, 
	"cholesterol": 85, 
	"sodium": 1960, 
	"total_carbs": 105, 
	"dietary_fiber": 7, 
	"sugar": 14, 
	"protein": 22, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Chipotle Adobo with Pork RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 580, 
	"calories_from_fat": 220, 
	"total_fat": 24, 
	"saturated_fat": 11, 
	"trans_fat": 0, 
	"cholesterol": 75, 
	"sodium": 1510, 
	"total_carbs": 53, 
	"dietary_fiber": 4, 
	"sugar": 7, 
	"protein": 33,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Chipotle Adobo with Pork SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 990, 
	"calories_from_fat": 380, 
	"total_fat": 42, 
	"saturated_fat": 19, 
	"trans_fat": 0.5, 
	"cholesterol": 120, 
	"sodium": 2460, 
	"total_carbs": 105, 
	"dietary_fiber": 7, 
	"sugar": 14, 
	"protein": 44, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Chipotle Adobo with Chicken RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 530, 
	"calories_from_fat": 180, 
	"total_fat": 20, 
	"saturated_fat": 9, 
	"trans_fat": 0, 
	"cholesterol": 95, 
	"sodium": 1380, 
	"total_carbs": 53, 
	"dietary_fiber": 4, 
	"sugar": 7, 
	"protein": 34,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Chipotle Adobo with Chicken SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 940, 
	"calories_from_fat": 340, 
	"total_fat": 38, 
	"saturated_fat": 17, 
	"trans_fat": 0.5, 
	"cholesterol": 140, 
	"sodium": 2330, 
	"total_carbs": 105, 
	"dietary_fiber": 7, 
	"sugar": 14, 
	"protein": 44, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Korean Beef Noodles RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 520, 
	"calories_from_fat": 130, 
	"total_fat": 15, 
	"saturated_fat": 3, 
	"trans_fat": 0, 
	"cholesterol": 50, 
	"sodium": 1930, 
	"total_carbs": 71, 
	"dietary_fiber": 3, 
	"sugar": 23, 
	"protein": 25,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Spicy Korean Beef Noodles SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 930, 
	"calories_from_fat": 220, 
	"total_fat": 24, 
	"saturated_fat": 4, 
	"trans_fat": 0, 
	"cholesterol": 50, 
	"sodium": 3590, 
	"total_carbs": 140, 
	"dietary_fiber": 5, 
	"sugar": 46, 
	"protein": 35, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Buttered Noodles RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 390, 
	"calories_from_fat": 160, 
	"total_fat": 17, 
	"saturated_fat": 8, 
	"trans_fat": 0, 
	"cholesterol": 110, 
	"sodium": 300, 
	"total_carbs": 50, 
	"dietary_fiber": 2, 
	"sugar": 3, 
	"protein": 11,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Buttered Noodles SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 760, 
	"calories_from_fat": 310, 
	"total_fat": 35, 
	"saturated_fat": 15, 
	"trans_fat": 1, 
	"cholesterol": 220, 
	"sodium": 600, 
	"total_carbs": 98, 
	"dietary_fiber": 4, 
	"sugar": 6, 
	"protein": 22, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Alfredo MontAmore® RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 810, 
	"calories_from_fat": 430, 
	"total_fat": 48, 
	"saturated_fat": 22, 
	"trans_fat": 1, 
	"cholesterol": 140, 
	"sodium": 1470, 
	"total_carbs": 61, 
	"dietary_fiber": 4, 
	"sugar": 7, 
	"protein": 32,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Alfredo MontAmore® SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 1420, 
	"calories_from_fat": 770, 
	"total_fat": 86, 
	"saturated_fat": 41, 
	"trans_fat": 2.5, 
	"cholesterol": 230, 
	"sodium": 2100, 
	"total_carbs": 112, 
	"dietary_fiber": 7, 
	"sugar": 13, 
	"protein": 47, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pasta Fresca with parmesan RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 440, 
	"calories_from_fat": 170, 
	"total_fat": 19, 
	"saturated_fat": 4, 
	"trans_fat": 0, 
	"cholesterol": 5, 
	"sodium": 920, 
	"total_carbs": 57, 
	"dietary_fiber": 2, 
	"sugar": 4, 
	"protein": 10,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pasta Fresca with parmesan SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 880, 
	"calories_from_fat": 340, 
	"total_fat": 38, 
	"saturated_fat": 8, 
	"trans_fat": 0, 
	"cholesterol": 15, 
	"sodium": 1840, 
	"total_carbs": 114, 
	"dietary_fiber": 5, 
	"sugar": 8, 
	"protein": 20, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pasta Fresca with feta RG",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 440, 
	"calories_from_fat": 170, 
	"total_fat": 19, 
	"saturated_fat": 4, 
	"trans_fat": 0, 
	"cholesterol": 5, 
	"sodium": 920, 
	"total_carbs": 57, 
	"dietary_fiber": 2, 
	"sugar": 4, 
	"protein": 10,
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
call_api(vendormenu_url, "createNutritionalFact", {
	"profile_name": "Pasta Fresca with feta SM",
	"cookie": temp_cookie,
	"serving_size": 10,
	"calories": 880, 
	"calories_from_fat": 340, 
	"total_fat": 38, 
	"saturated_fat": 8, 
	"trans_fat": 0, 
	"cholesterol": 15, 
	"sodium": 1840, 
	"total_carbs": 114, 
	"dietary_fiber": 5, 
	"sugar": 8, 
	"protein": 20, 
	"vitamin_a": 0,
	"vitamin_b": 0,
	"vitamin_c": 0,
	"vitamin_d": 0,
	"calcium": 0,
	"iron": 0
});
